name: Deploy Portfolio Autom√°tico
on:
  push:
    branches: [ main ] # Se sua branch no GitHub for 'master', mude aqui para master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalando e Gerando Site (Build)
        run: |
          npm install
          npm run build
      - name: Enviando Arquivos para HostGator
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./public_html/portfolio/
